scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: 'docker-details'
    static_configs:
      - targets:
          - cadvisor:8080